#!/bin/bash
# Path
WALCSS="$HOME/.cache/wal/colors.css"
BDCSS="$HOME/.config/BetterDiscord/data/stable/custom.css"
TEMPLATE="$HOME/.config/BetterDiscord/bd-template.css"
HEADER="$HOME/.config/BetterDiscord/bd-header.css"

# Overwrite Better Discord Custom CSS using pywal color palette
cat "$HEADER" > "$BDCSS"
echo "" >> "$BDCSS"
cat "$WALCSS" >> "$BDCSS"
echo "" >> "$BDCSS"

# Extract current wallpaper from gsettings
CURRENT_WALLPAPER=$(gsettings get org.gnome.desktop.background picture-uri-dark 2>/dev/null || echo "")

if [ -n "$CURRENT_WALLPAPER" ] && [ "$CURRENT_WALLPAPER" != "''" ]; then
    # gsettings wraps output in single quotes: 'file:///path/to/file.png'
    # Strip leading '  and trailing '  then remove file:// prefix
    WALLPAPER_PATH=$(echo "$CURRENT_WALLPAPER" | sed "s/^'//; s/'$//; s/\"$//; s|^file://||")

    # Extract filename safely
    WALLPAPER_NAME=$(basename -- "$WALLPAPER_PATH")

    # Generate GitHub URL
    GITHUB_WALLPAPER_URL="https://raw.githubusercontent.com/SeraphimeZelel/rion-ricing/refs/heads/main/Wallpaper/$WALLPAPER_NAME"

cat >> "$BDCSS" << EOF
/* Wallpaper URL - Generated by discord-pywalsync.sh */
:root {
    --wallpaper: url("$GITHUB_WALLPAPER_URL");
}
EOF
    echo "" >> "$BDCSS"
fi

cat "$TEMPLATE" >> "$BDCSS"